# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'BridgeCard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BridgeCard
    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
        'Core',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'ART'
    ]
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKPlacesKit'
    pod 'FBSDKMessengerShareKit'
    pod 'FBSDKLoginKit'

    pod 'GoogleSignIn', '~> 4.0'
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'

    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

    pod 'Firebase/Core', '~> 5.14.0'
    pod 'Firebase/Database', '~> 5.14.0'
    pod 'Firebase/Auth', '~> 5.14.0'
    pod 'FirebaseAnalytics', '~> 5.4.0'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    # pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

    pod 'RNIap', :path => '../node_modules/react-native-iap'

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
