# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BridgeCard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BridgeCard
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
  target 'BridgeCard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'react-native-webgl', :path => '../node_modules/react-native-webgl'

  end

  target 'BridgeCardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
